version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
    - run:
          name: install electron
          command: npm install electron
     - run:
          name: Run tests
          command: npm start




